<template>
    <ion-page>
        <ion-header>
            <ion-toolbar>
                <ion-title>MQTT Protocol</ion-title>
                <ion-buttons slot="end">
                    <ion-button @click="dismissModal()">Close</ion-button>
                </ion-buttons>
            </ion-toolbar>
        </ion-header>
        <ion-content class="ion-padding">
            <p>
                This app supports MQTT over <strong>WebSocket</strong> <code>ws://</code> and <strong>WebSocket Secure</strong> <code>wss://</code> protocols.
            </p>
            <p>
                The difference between the two is <code>ws://</code> is unencrypted while <code>wss://</code> is encrypted. <code>ws://</code> will be slightly faster if you do not need encryption.
            </p>
            <p>
                Note that if you choose to use the <code>wss://</code> you will need to install a SSL certificate on your phone generated by the MQTT Broker or it will not work.
            </p>
            <ion-button expand="block" fill="clear" @click="dismissModal()">Got it <ion-icon :icon="chevronForwardCircleOutline" class="ion-margin-start ion-margin-tiny" /></ion-button>
        </ion-content>
    </ion-page>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { modalController } from '@ionic/vue';
import { chevronForwardCircleOutline } from 'ionicons/icons';
import { mqttBrokerDownloadUrl } from '@/constants';

export default defineComponent({
    props: {
        isLikelyUsingOurBroker: {
            type: Boolean,
            default: false
        }
    },
    setup() {
        function dismissModal(args: any) {
            modalController.dismiss(args);
        }

        return {
            mqttBrokerDownloadUrl,
            dismissModal,
            chevronForwardCircleOutline
        };
    }
});
</script>
